# Generated by Django 5.2.17 on 2026-10-04 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='erstellt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='abgeschlossen')),
                ('kind', models.CharField(choices=[('phone', 'Rufnummer'), ('ip', 'IP-Adresse')], max_length=10, verbose_name='Typ')),
                ('query', models.CharField(db_index=True, max_length=64, verbose_name='Abfrage')),
                ('status', models.CharField(choices=[('pending', 'Wartet'), ('collecting', 'Quellen werden abgefragt'), ('analyzing', 'KI schreibt den Bericht'), ('done', 'Fertig'), ('failed', 'Fehler')], default='pending', max_length=12)),
                ('risk', models.CharField(blank=True, choices=[('niedrig', 'niedrig'), ('mittel', 'mittel'), ('hoch', 'hoch'), ('unklar', 'unklar')], max_length=10, verbose_name='Risiko')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='KI-Modell')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='Rohdaten')),
                ('report_md', models.TextField(blank=True, verbose_name='Bericht')),
                ('error', models.TextField(blank=True, verbose_name='Fehler')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyse',
                'verbose_name_plural': 'Analysen',
                'ordering': ['-created_at'],
            },
        ),
    ]
