# Generated by Django 5.2.17 on 2026-10-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='kind',
            field=models.CharField(choices=[('phone', 'Rufnummer'), ('ip', 'IP-Adresse'), ('host', 'Hostname')], max_length=10, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='query',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Abfrage'),
        ),
    ]
