# Generated by Django 5.2.17 on 2026-10-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_alter_lookup_kind_alter_lookup_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='active_probe',
            field=models.BooleanField(default=False, help_text='Ziel direkt kontaktieren (TLS-Zertifikat, Web-Kopfzeilen); erscheint im Log des Ziels.', verbose_name='leise aktiv'),
        ),
    ]
