# Generated by Django 5.2.17 on 2026-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0003_lookup_active_probe'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='z. B. 203.0.113.7, 203.0.113.0/24 oder meinserver.example.org. Hostnamen gelten nur exakt (keine Subdomains).', max_length=255, unique=True, verbose_name='Adresse oder Hostname')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='eingetragen')),
            ],
            options={
                'verbose_name': 'Eigenes System',
                'verbose_name_plural': 'Eigene Systeme',
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='lookup',
            name='port_scan',
            field=models.BooleanField(default=False, help_text='nmap-Portscan; nur für Ziele aus der Liste der eigenen Systeme.', verbose_name='Portscan'),
        ),
    ]
