# Generated by Django 5.2.17 on 2026-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0004_ownedtarget_and_port_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedtarget',
            name='asn',
            field=models.CharField(blank=True, help_text='Bei Hostnamen erforderlich, z. B. AS3320 (Telekom). Ein Name beweist nicht, wem die Adresse gehört, auf die er zeigt; gescannt wird nur, wenn alle seine Adressen in diesen Netzen liegen. Die AS-Nummer steht im ASN-Block einer Analyse.', max_length=100, verbose_name='Erlaubte Netze (AS-Nummer)'),
        ),
    ]
