# Generated by Django 5.2.17 on 2026-10-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0005_ownedtarget_asn'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='as_of',
            field=models.DateField(blank=True, help_text='Rückblick: Historische Quellen (BGP, Passive DNS) für dieses Datum auswerten.', null=True, verbose_name='Stand'),
        ),
    ]
