# Generated by Django 5.2.17 on 2026-10-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0006_lookup_as_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Notiz'),
        ),
    ]
