# Generated by Django 5.2 on 2026-10-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0008_lookup_fritzbox_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookup",
            name="active_profile",
            field=models.CharField(
                choices=[("fritzbox", "FRITZ!Box"), ("generic-router", "Generischer Router")],
                default="fritzbox", help_text="Ausdrücklich ausgewähltes, nicht destruktives aktives Prüfprofil.",
                max_length=20, verbose_name="aktives Profil",
            ),
        ),
        migrations.AddField(
            model_name="lookup",
            name="enrichment_of",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name="+", to="lookups.lookup", verbose_name="angereichert aus"),
        ),
    ]
