# Generated by Django 5.2.17 on 2026-10-04 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='z. B. example.org. Subdomains müssen einzeln eingetragen werden. Ist keine Domain eingetragen, ist jede Domain erlaubt.', max_length=253, unique=True, verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Erlaubte Domain',
                'verbose_name_plural': 'Erlaubte Domains',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='erstellt')),
                ('expires_at', models.DateTimeField(verbose_name='gültig bis')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='eingelöst')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='erstellt von')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrierter Nutzer')),
            ],
            options={
                'verbose_name': 'Einladung',
                'verbose_name_plural': 'Einladungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
