# Generated by Django 5.2.17 on 2026-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-Mail bestätigt'),
        ),
    ]
